[project]
name = "assistant"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "openai>=2.1.0",
    "pydantic-settings>=2.11.0",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]


