[project]
name = "backend"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "plexapi>=4.17.1",
    "pydantic-settings>=2.11.0",
    "pytz>=2025.2",
    "uvicorn>=0.37.0",
]

