[project]
name = "frontend"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.28.0",
    "streamlit-autorefresh>=1.0.1",
    "streamlit-extras>=0.7.8",
    "websocket-client>=1.8.0",
    "websockets>=15.0.1",
]

